# Basic
title: Salty World
subtitle: 做人最紧要开心~
welcome_message: 玩玩最新的<a href="https://saltyleung.github.io/products/" target="_blank">好咸在线随机数生成器</a>试一下？~
description: 这里是好咸的地盘 (@VerySalty)，欢迎随便践踏。
creator: <a href="http://baidu.com">@onevcat</a>

url: "http://baidu.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

blog_button:
    title: 搞事
    description: 搞事情
nav:
    - {title: 搞机, description: 搞计算机, url: 'https://saltyleung.github.io/products/PC'}
    - {title: 搞笑, description: 就是搞笑, url: 'https://saltyleung.github.io/products/LPH'}
    - {title: 膜, description: □-□, url: 'https:/saltyleung.github.io/products/'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: onevcat
    # duoshuo:
# Social
social:
    weibo: verysalty
    github: SaltyLeung
    twitter: 
    gplus: 
    mail: 498546830@qq.com

# Google Analytics
ga:
    id: 
    host: 
