# Basic
title: Welcome to a Salty World!
subtitle: 做人最紧要开心~
welcome_message: 玩玩最新的<a href="https://objccn.io/products/" target="_blank">好咸在线随机数生成器</a>试一下？~
description: 这里是好咸的地盘 (@VerySalty)，欢迎随便践踏。
creator: <a href="http://baidu.com">@onevcat</a>

url: "http://baidu.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

blog_button:
    title: 搞事
    description: 搞事情
nav:
    - {title: 项目, description: 我的项目, url: 'http://project.onevcat.com'}
    - {title: 关于, description: 了解更多关于我, url: 'http://about.onevcat.com/'}
    - {title: 订阅, description: 邮件订阅本站, url: '//store.objccn.io/subscribe'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: onevcat
    # duoshuo:
# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: onev@onevcat.com

# Google Analytics
ga:
    id: UA-25719337-1
    host: onevcat.com
